"""Tests for MCP tool definitions, OpenAPI converter, and service routing."""

import pytest
from app.openapi.parser import OpenAPIEndpoint
from app.openapi.converter import (
    generate_tool_name,
    build_input_schema,
    map_openapi_type,
    _build_description,
    endpoint_to_mcp_tool,
)
from app.domains.manager import DomainManager
from app.routers.tools import ToolCallRequest, ToolListResponse


# ============================================================
# generate_tool_name
# ============================================================

class TestGenerateToolName:
    """Tests for MCP tool name generation from OpenAPI endpoints."""

    def test_uses_clean_operation_id(self, make_endpoint):
        ep = make_endpoint(operation_id="search_corporation")
        assert generate_tool_name(ep) == "search_corporation"

    def test_strips_api_suffix_from_autogenerated_id(self, make_endpoint):
        ep = make_endpoint(operation_id="get_stats_api_market_stats_get")
        assert generate_tool_name(ep) == "get_stats"

    def test_fallback_to_path_when_no_operation_id(self, make_endpoint):
        ep = make_endpoint(operation_id="", path="/api/market/price/{type_id}", method="GET")
        name = generate_tool_name(ep)
        assert name == "get_market_price_type_id"

    def test_fallback_removes_api_prefix(self, make_endpoint):
        ep = make_endpoint(operation_id="", path="/api/war/losses", method="GET")
        assert generate_tool_name(ep) == "get_war_losses"

    def test_post_method_prefix(self, make_endpoint):
        ep = make_endpoint(operation_id="", path="/api/market/bulk", method="POST")
        assert generate_tool_name(ep) == "post_market_bulk"

    def test_delete_method_prefix(self, make_endpoint):
        ep = make_endpoint(operation_id="", path="/api/shopping/lists/1", method="DELETE")
        name = generate_tool_name(ep)
        assert name.startswith("delete_")

    @pytest.mark.parametrize("op_id,expected", [
        ("list_battles", "list_battles"),
        ("get_items_api_items_search_get", "get_items"),
        ("create_api_views_post", "create"),
    ])
    def test_operation_id_cleanup(self, make_endpoint, op_id, expected):
        ep = make_endpoint(operation_id=op_id)
        assert generate_tool_name(ep) == expected


# ============================================================
# map_openapi_type
# ============================================================

class TestMapOpenAPIType:
    """Tests for OpenAPI to JSON Schema type mapping."""

    @pytest.mark.parametrize("openapi_type,expected", [
        ("integer", "integer"),
        ("number", "number"),
        ("string", "string"),
        ("boolean", "boolean"),
        ("array", "array"),
        ("object", "object"),
    ])
    def test_known_types(self, openapi_type, expected):
        assert map_openapi_type(openapi_type) == expected

    @pytest.mark.parametrize("unknown", ["int", "float", "date-time", "binary", ""])
    def test_unknown_types_fallback_to_string(self, unknown):
        assert map_openapi_type(unknown) == "string"


# ============================================================
# _build_description
# ============================================================

class TestBuildDescription:
    """Tests for tool description generation."""

    def test_summary_only(self, make_endpoint):
        ep = make_endpoint(summary="Get market stats", description="")
        assert _build_description(ep) == "Get market stats"

    def test_description_only(self, make_endpoint):
        ep = make_endpoint(summary="", description="Detailed info about market.")
        assert _build_description(ep) == "Detailed info about market."

    def test_summary_and_description_combined(self, make_endpoint):
        ep = make_endpoint(summary="Get stats", description="Returns detailed market statistics.")
        result = _build_description(ep)
        assert "Get stats" in result
        assert "Returns detailed market statistics." in result

    def test_identical_summary_and_description_deduped(self, make_endpoint):
        ep = make_endpoint(summary="Get stats", description="Get stats")
        assert _build_description(ep) == "Get stats"

    def test_empty_returns_fallback(self, make_endpoint):
        ep = make_endpoint(summary="", description="")
        assert _build_description(ep) == "No description available"


# ============================================================
# build_input_schema
# ============================================================

class TestBuildInputSchema:
    """Tests for MCP input schema generation from OpenAPI parameters."""

    def test_path_parameter(self, make_endpoint):
        ep = make_endpoint(parameters=[{
            "name": "type_id",
            "in": "path",
            "required": True,
            "schema": {"type": "integer"},
        }])
        schema = build_input_schema(ep)
        assert schema["type"] == "object"
        assert "type_id" in schema["properties"]
        assert schema["properties"]["type_id"]["type"] == "integer"
        assert "type_id" in schema["required"]

    def test_query_parameter_with_default(self, make_endpoint):
        ep = make_endpoint(parameters=[{
            "name": "region_id",
            "in": "query",
            "required": False,
            "schema": {"type": "integer", "default": 10000002},
            "description": "The Forge region",
        }])
        schema = build_input_schema(ep)
        props = schema["properties"]
        assert props["region_id"]["default"] == 10000002
        assert props["region_id"]["description"] == "The Forge region"
        assert "region_id" not in schema["required"]

    def test_request_body_properties(self, make_endpoint):
        ep = make_endpoint(
            method="POST",
            request_body={
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string", "description": "List name"},
                                "quantity": {"type": "integer"},
                            },
                            "required": ["name"],
                        }
                    }
                }
            },
        )
        schema = build_input_schema(ep)
        assert "name" in schema["properties"]
        assert "quantity" in schema["properties"]
        assert "name" in schema["required"]

    def test_no_parameters_returns_empty_schema(self, make_endpoint):
        ep = make_endpoint(parameters=[], request_body=None)
        schema = build_input_schema(ep)
        assert schema == {"type": "object", "properties": {}, "required": []}

    def test_required_deduplication(self, make_endpoint):
        """If same param is in both path params and body required, no duplicates."""
        ep = make_endpoint(
            parameters=[{
                "name": "id",
                "in": "path",
                "required": True,
                "schema": {"type": "integer"},
            }],
            request_body={
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {"id": {"type": "integer"}},
                            "required": ["id"],
                        }
                    }
                }
            },
        )
        schema = build_input_schema(ep)
        assert schema["required"].count("id") == 1

    def test_param_without_name_skipped(self, make_endpoint):
        ep = make_endpoint(parameters=[{"in": "query", "schema": {"type": "string"}}])
        schema = build_input_schema(ep)
        assert schema["properties"] == {}


# ============================================================
# endpoint_to_mcp_tool (integration of above)
# ============================================================

class TestEndpointToMcpTool:
    """Tests for full OpenAPI-to-MCP tool conversion."""

    def test_complete_tool_structure(self, make_endpoint):
        ep = make_endpoint(
            service="war_intel",
            method="GET",
            path="/api/mcp/search",
            operation_id="search_corporation",
            summary="Search corps",
        )
        tool = endpoint_to_mcp_tool(ep)
        assert tool["name"] == "search_corporation"
        assert "Search corps" in tool["description"]
        assert tool["inputSchema"]["type"] == "object"
        assert tool["_metadata"]["service"] == "war_intel"
        assert tool["_metadata"]["method"] == "GET"
        assert tool["_metadata"]["path"] == "/api/mcp/search"

    def test_metadata_includes_operation_id(self, make_endpoint):
        ep = make_endpoint(operation_id="my_op")
        tool = endpoint_to_mcp_tool(ep)
        assert tool["_metadata"]["operation_id"] == "my_op"


# ============================================================
# OpenAPIEndpoint model validation
# ============================================================

class TestOpenAPIEndpointModel:
    """Tests for the Pydantic OpenAPIEndpoint model."""

    def test_valid_creation(self):
        ep = OpenAPIEndpoint(
            service="market",
            method="GET",
            path="/api/test",
            operation_id="test_op",
            summary="Test",
            description="Desc",
            parameters=[],
            responses={},
            tags=["market"],
        )
        assert ep.service == "market"
        assert ep.request_body is None

    def test_request_body_optional(self):
        ep = OpenAPIEndpoint(
            service="s", method="GET", path="/p", operation_id="o",
            summary="", description="", parameters=[], responses={}, tags=[],
        )
        assert ep.request_body is None


# ============================================================
# Pydantic request/response models
# ============================================================

class TestRouterModels:
    """Tests for MCP router Pydantic models."""

    def test_tool_call_request_defaults(self):
        req = ToolCallRequest(name="get_regions")
        assert req.name == "get_regions"
        assert req.arguments == {}

    def test_tool_call_request_with_args(self):
        req = ToolCallRequest(name="search", arguments={"q": "Drake"})
        assert req.arguments["q"] == "Drake"

    def test_tool_list_response(self):
        resp = ToolListResponse(
            tools=[{"name": "t1"}],
            count=1,
            categories={"market": 1, "total": 1},
        )
        assert resp.count == 1
        assert resp.categories["total"] == 1


# ============================================================
# MCPConfig
# ============================================================

class TestMCPConfig:
    """Tests for MCP service configuration."""

    def test_cors_wildcard(self):
        from app.config import MCPConfig
        cfg = MCPConfig()
        assert cfg.cors_origin_list == ["*"]

    def test_cors_csv_parsing(self):
        from app.config import MCPConfig
        cfg = MCPConfig(cors_origins="http://a.com, http://b.com")
        assert cfg.cors_origin_list == ["http://a.com", "http://b.com"]

    def test_cors_empty_entries_filtered(self):
        from app.config import MCPConfig
        cfg = MCPConfig(cors_origins="http://a.com, , ,http://b.com")
        assert cfg.cors_origin_list == ["http://a.com", "http://b.com"]


# ============================================================
# DomainManager (unit tests, no async)
# ============================================================

class TestDomainManager:
    """Tests for DomainManager domain switching and tool retrieval."""

    def test_services_dict_has_expected_domains(self):
        dm = DomainManager()
        assert "market" in dm.SERVICES
        assert "war_intel" in dm.SERVICES
        assert "production" in dm.SERVICES

    def test_initial_state_no_active_domain(self):
        dm = DomainManager()
        assert dm.active_domain is None

    def test_get_active_tools_returns_switchers_when_no_domain(self):
        dm = DomainManager()
        tools = dm.get_active_tools()
        # Should return domain switcher tools
        assert all("_domain_switch" in t for t in tools)

    def test_domain_switcher_names(self):
        dm = DomainManager()
        switchers = dm._get_domain_switchers()
        names = [t["name"] for t in switchers]
        assert "enable_market_tools" in names
        assert "enable_war_intel_tools" in names

    def test_domain_switcher_has_input_schema(self):
        dm = DomainManager()
        switchers = dm._get_domain_switchers()
        for s in switchers:
            assert s["inputSchema"]["type"] == "object"
            assert "properties" in s["inputSchema"]

    def test_get_active_tools_returns_domain_tools_when_active(self):
        dm = DomainManager()
        dm.domain_tools["market"] = [{"name": "price_check"}]
        dm.active_domain = "market"
        tools = dm.get_active_tools()
        assert tools == [{"name": "price_check"}]

    def test_get_active_tools_empty_domain(self):
        dm = DomainManager()
        dm.active_domain = "market"
        # No tools loaded for market
        tools = dm.get_active_tools()
        assert tools == []


# ============================================================
# ServiceProxy routing
# ============================================================

class TestServiceProxyRouting:
    """Tests for ServiceProxy._get_service_url endpoint routing."""

    def test_market_routing(self):
        from app.services.tool_registry import ServiceProxy
        proxy = ServiceProxy()
        url = proxy._get_service_url("/api/market/stats")
        assert "localhost:8004" in url

    def test_war_intel_routing(self):
        from app.services.tool_registry import ServiceProxy
        proxy = ServiceProxy()
        url = proxy._get_service_url("/api/war/losses")
        assert "localhost:8002" in url

    def test_production_routing(self):
        from app.services.tool_registry import ServiceProxy
        proxy = ServiceProxy()
        url = proxy._get_service_url("/api/production/cost")
        assert "localhost:8005" in url

    def test_unknown_endpoint_falls_back_to_monolith(self):
        from app.services.tool_registry import ServiceProxy
        proxy = ServiceProxy()
        url = proxy._get_service_url("/api/unknown/thing")
        assert "localhost:8000" in url

    @pytest.mark.parametrize("prefix,port", [
        ("/api/auth", "8001"),
        ("/api/shopping", "8006"),
        ("/api/character", "8007"),
        ("/api/scheduler", "8003"),
        ("/api/fittings", "8007"),
        ("/api/skills", "8007"),
    ])
    def test_service_route_prefixes(self, prefix, port):
        from app.services.tool_registry import ServiceProxy
        proxy = ServiceProxy()
        url = proxy._get_service_url(prefix + "/something")
        assert port in url


# ============================================================
# ToolRegistry (global instance)
# ============================================================

class TestToolRegistry:
    """Tests for the global ToolRegistry instance."""

    def test_registry_has_tools(self):
        from app.services.tool_registry import tool_registry
        tools = tool_registry.get_all_tools()
        assert len(tools) > 0

    def test_get_tool_by_name(self):
        from app.services.tool_registry import tool_registry
        tool = tool_registry.get_tool("get_regions")
        assert tool is not None
        assert tool["name"] == "get_regions"

    def test_get_tool_returns_none_for_unknown(self):
        from app.services.tool_registry import tool_registry
        assert tool_registry.get_tool("nonexistent_tool_xyz") is None

    def test_get_handler_returns_callable(self):
        from app.services.tool_registry import tool_registry
        handler = tool_registry.get_handler("get_regions")
        assert handler is not None
        assert callable(handler)

    def test_get_handler_returns_none_for_unknown(self):
        from app.services.tool_registry import tool_registry
        assert tool_registry.get_handler("nonexistent_tool_xyz") is None

    def test_category_counts_include_total(self):
        from app.services.tool_registry import tool_registry
        counts = tool_registry.get_tool_counts()
        assert "total" in counts
        assert counts["total"] == len(tool_registry.get_all_tools())

    def test_all_tools_have_required_keys(self):
        from app.services.tool_registry import tool_registry
        for tool in tool_registry.get_all_tools():
            assert "name" in tool
            assert "description" in tool
            assert "category" in tool

    def test_registered_tool_names_unique(self):
        from app.services.tool_registry import tool_registry
        names = [t["name"] for t in tool_registry.get_all_tools()]
        assert len(names) == len(set(names)), "Duplicate tool names found"


# ============================================================
# OpenAPIParser.parse_endpoints (with pre-loaded spec)
# ============================================================

class TestOpenAPIParser:
    """Tests for OpenAPI spec parsing logic."""

    def test_parse_simple_spec(self):
        from app.openapi.parser import OpenAPIParser
        parser = OpenAPIParser()
        parser.specs["test_svc"] = {
            "paths": {
                "/api/test": {
                    "get": {
                        "operationId": "get_test",
                        "summary": "Test endpoint",
                        "description": "",
                        "parameters": [],
                        "responses": {"200": {}},
                        "tags": ["test"],
                    }
                }
            }
        }
        endpoints = parser.parse_endpoints("test_svc")
        assert len(endpoints) == 1
        assert endpoints[0].operation_id == "get_test"
        assert endpoints[0].method == "GET"

    def test_parse_filters_mcp_only(self):
        from app.openapi.parser import OpenAPIParser
        parser = OpenAPIParser()
        parser.specs["svc"] = {
            "paths": {
                "/api/test": {"get": {"operationId": "a", "summary": "", "description": "",
                                       "parameters": [], "responses": {}, "tags": []}},
                "/api/mcp/search": {"get": {"operationId": "b", "summary": "", "description": "",
                                             "parameters": [], "responses": {}, "tags": []}},
            }
        }
        all_eps = parser.parse_endpoints("svc", mcp_only=False)
        assert len(all_eps) == 2

        mcp_eps = parser.parse_endpoints("svc", mcp_only=True)
        assert len(mcp_eps) == 1
        assert mcp_eps[0].operation_id == "b"

    def test_parse_ignores_non_http_methods(self):
        from app.openapi.parser import OpenAPIParser
        parser = OpenAPIParser()
        parser.specs["svc"] = {
            "paths": {
                "/api/test": {
                    "get": {"operationId": "ok", "summary": "", "description": "",
                            "parameters": [], "responses": {}, "tags": []},
                    "parameters": [{"name": "shared"}],  # path-level params, not a method
                }
            }
        }
        endpoints = parser.parse_endpoints("svc")
        assert len(endpoints) == 1

    def test_parse_no_spec_returns_empty(self):
        from app.openapi.parser import OpenAPIParser
        parser = OpenAPIParser()
        assert parser.parse_endpoints("unknown_service") == []

    def test_parse_multiple_methods(self):
        from app.openapi.parser import OpenAPIParser
        parser = OpenAPIParser()
        parser.specs["svc"] = {
            "paths": {
                "/api/items": {
                    "get": {"operationId": "list", "summary": "", "description": "",
                            "parameters": [], "responses": {}, "tags": []},
                    "post": {"operationId": "create", "summary": "", "description": "",
                             "parameters": [], "responses": {}, "tags": []},
                }
            }
        }
        endpoints = parser.parse_endpoints("svc")
        methods = {ep.method for ep in endpoints}
        assert methods == {"GET", "POST"}


# ============================================================
# GenericAPIHandler constants
# ============================================================

class TestGenericAPIHandler:
    """Tests for GenericAPIHandler service URL routing."""

    def test_service_urls_contain_all_domains(self):
        from app.handlers.generic_api import GenericAPIHandler
        handler = GenericAPIHandler()
        assert "market" in handler.SERVICE_URLS
        assert "war_intel" in handler.SERVICE_URLS
        assert "wormhole" in handler.SERVICE_URLS

    def test_service_urls_are_http(self):
        from app.handlers.generic_api import GenericAPIHandler
        handler = GenericAPIHandler()
        for url in handler.SERVICE_URLS.values():
            assert url.startswith("http://")
