"""fitting_stats package — public API re-exports."""

# Models
from .models import (
    FittingStatsRequest,
    FittingStatsResponse,
    SlotUsage,
    ResourceUsage,
    DamageBreakdown,
    ResistProfile,
    OffenseStats,
    DefenseStats,
    CapacitorStats,
    NavigationStats,
    TargetingStats,
    RepairStats,
    TargetProfile,
    AppliedDPS,
)

# Pure calculation functions
from .calculations import (
    calculate_capacitor,
    calculate_align_time,
    calculate_lock_time,
    calculate_shield_peak_regen,
    calculate_rep_rate,
    calculate_weapon_dps,
    calculate_drone_dps,
    calculate_turret_hit_chance,
    calculate_missile_application,
    calculate_warp_time,
    calculate_effective_rep,
    calculate_scanability,
)

# Constants
from .constants import (
    ATTR_HI_SLOTS,
    ATTR_MED_SLOTS,
    ATTR_LOW_SLOTS,
    ATTR_RIG_SLOTS,
    ATTR_POWER_OUTPUT,
    ATTR_CPU_OUTPUT,
    ATTR_CPU_NEED,
    ATTR_POWER_NEED,
    ATTR_MAX_VELOCITY,
    ATTR_AGILITY,
    ATTR_SIG_RADIUS,
    ATTR_CALIBRATION_OUTPUT,
    ATTR_CALIBRATION_COST,
    ATTR_TURRET_SLOTS,
    ATTR_LAUNCHER_SLOTS,
    ATTR_CAP_CAPACITY,
    ATTR_CAP_RECHARGE,
    ATTR_DRONE_CAPACITY,
    ATTR_DRONE_BANDWIDTH,
    ATTR_MAX_TARGET_RANGE,
    ATTR_SCAN_RES,
    ATTR_MAX_LOCKED,
    ATTR_SCAN_RADAR,
    ATTR_SCAN_LADAR,
    ATTR_SCAN_MAGNETO,
    ATTR_SCAN_GRAVI,
    ATTR_WARP_SPEED_MULT,
    ATTR_MASS,
    ATTR_CAP_NEED,
    ATTR_DURATION,
    ATTR_RATE_OF_FIRE,
    ATTR_DRONE_BW_NEED,
    ATTR_VOLUME,
    ATTR_DAMAGE_MULT,
    ATTR_EM_DAMAGE,
    ATTR_EXPLOSIVE_DAMAGE,
    ATTR_KINETIC_DAMAGE,
    ATTR_THERMAL_DAMAGE,
    ATTR_META_LEVEL,
    ATTR_CHARGE_GROUP1,
    ATTR_CHARGE_GROUP2,
    ATTR_CHARGE_GROUP3,
    ATTR_CHARGE_GROUP4,
    ATTR_CHARGE_GROUP5,
    ATTR_SHIELD_RECHARGE,
    ATTR_SHIELD_HP,
    ATTR_ARMOR_HP,
    ATTR_HULL_HP,
    ATTR_SHIELD_EM_RESIST,
    ATTR_SHIELD_THERMAL_RESIST,
    ATTR_SHIELD_KINETIC_RESIST,
    ATTR_SHIELD_EXPLOSIVE_RESIST,
    ATTR_ARMOR_EM_RESIST,
    ATTR_ARMOR_THERMAL_RESIST,
    ATTR_ARMOR_KINETIC_RESIST,
    ATTR_ARMOR_EXPLOSIVE_RESIST,
    ATTR_HULL_EM_RESIST,
    ATTR_HULL_THERMAL_RESIST,
    ATTR_HULL_KINETIC_RESIST,
    ATTR_HULL_EXPLOSIVE_RESIST,
    ATTR_SHIELD_BOOST_AMOUNT,
    ATTR_ARMOR_REPAIR_AMOUNT,
    ATTR_HULL_REPAIR_AMOUNT,
    ATTR_DRONE_CONTROL_RANGE,
    ATTR_CARGO_CAPACITY,
    ATTR_MAX_ACTIVE_DRONES,
    ATTR_SIG_RADIUS_MOD,
    FLAG_DRONE_BAY,
    EFFECT_AFTERBURNER,
    EFFECT_MWD,
    ATTR_SPEED_BOOST_FACTOR,
    ATTR_SPEED_FACTOR,
    ATTR_MASS_ADDITION,
    EFFECT_TURRET_FITTED,
    EFFECT_LAUNCHER_FITTED,
    SKILL_WEAPON_UPGRADES,
    SKILL_ADVANCED_WEAPON_UPGRADES,
    DEFAULT_FITTING_SKILL_LEVEL,
    SKILL_ACCELERATION_CONTROL,
    SKILL_DRONE_INTERFACING,
    TARGET_PROFILES,
    DAMAGE_PROFILES,
)

# Service
from .service import FittingStatsService
